-----------------------------------------------
-- JFD'S RULE WITH FAITH
-----------------------------------------------
CREATE TABLE IF NOT EXISTS 
	Civilization_Titles (
	CivilizationType  				text 		 		default null,
	GovernmentType					text 	 			default null,
	LeaderTitle						text				default null,
	PolicyType  					text 		 		default null);

CREATE TABLE IF NOT EXISTS 
	Leader_Titles (
	LeaderType  			text 		 		DEFAULT NULL,
	GovernmentType			text 	 			DEFAULT NULL,
	LeaderTitle				text				DEFAULT NULL,
	PolicyType  			text 		 		DEFAULT NULL,
	UseFeminine				BOOLEAN				DEFAULT 0,
	TitleIsFullName			BOOLEAN				DEFAULT 0);
	
INSERT INTO Civilization_Titles
		(CivilizationType, 				GovernmentType, 							PolicyType,				LeaderTitle)
VALUES	('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SASANIAN'),						--Chiefdom	-- Salar
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SASANIAN'),						--Horde	-- Marzb?n
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SASANIAN'),						--Polis -- Mobed
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SASANIAN'),					--Autocracy -- Š?h
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SASANIAN'),					--Oligarchy -- ?z?d
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SASANIAN'),			--Classical Democracy -- Wuzurg
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SASANIAN'),				--Feudal Monarchy -- Š?hanš?h
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SASANIAN'),			--Merchant Republic -- Kirrogbed
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_THEOCRACY',						null,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SASANIAN'),			--Theocracy -- Mobadan Mobad
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SASANIAN'),						--Absolute Monarchy -- Š?hanš?h
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SASANIAN'),						--Constitutional Monarchy -- Š?hanš?h
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SASANIAN'),					--Noble Republic -- Darandarzbad
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SASANIAN'),			--Liberal Democracy -- Wuzurg-fram?d?r
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SASANIAN'),				--People's Republic -- Š?hanš?h
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SASANIAN'),		--Military Guardianship -- ?r?n-sp?hbed
		('CIVILIZATION_CVS_SASANIAN',	null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SASANIAN'),						--Empire -- Š?hanš?h
		
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_CVS_SASANIAN_FEMININE'),					--Chiefdom	-- Salar
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_CVS_SASANIAN_FEMININE'),						--Horde	-- Marzb?n
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_CVS_SASANIAN_FEMININE'),						--Polis -- Mobed
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),					--Autocracy -- B?nbišn
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),					--Oligarchy -- ?z?d
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),		--Classical Democracy -- Wuzurg
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_FEUDAL_MONARCHY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),			--Feudal Monarchy -- B?nbišnan B?nbišn
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_CVS_SASANIAN_FEMININE'),			--Merchant Republic -- Kirrogbed
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_THEOCRACY',						null,					'LOC_GOVERNMENT_JFD_GOVERNMENT_THEOCRACY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),		--Theocracy -- Mobed?n Mobed
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),					--Absolute Monarchy -- B?nbišnan B?nbišn
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),					--Constitutional Monarchy -- B?nbišnan B?nbišn
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),					--Noble Republic -- Darandarzbad
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_CVS_SASANIAN_FEMININE'),			--Liberal Democracy -- Wuzurg-fram?d?r
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_CVS_SASANIAN_FEMININE'),			--People's Republic -- B?nbišnan B?nbišn
		('CIVILIZATION_CVS_SASANIAN',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_CVS_SASANIAN_FEMININE'),		--Military Guardianship -- ?r?n-sp?hbed
		('CIVILIZATION_CVS_SASANIAN',	null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_CVS_SASANIAN_FEMININE');					--Empire -- B?nbišnan B?nbišn
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_SASANIAN' AND GovernmentType IS NOT null AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_CVS_SASANIAN' AND PolicyType IS NOT null AND PolicyType NOT IN (SELECT PolicyType FROM Policies);				

-- And then in case the update hasn't come out yet:

INSERT INTO Leader_Titles
				(LeaderType, 					GovernmentType, 							PolicyType,				LeaderTitle)
SELECT DISTINCT	'LEADER_CVS_KAWAD_I',			GovernmentType, 							PolicyType,				LeaderTitle
FROM Civilization_Titles WHERE LeaderTitle NOT LIKE "%FEMININE" AND CivilizationType = 'CIVILIZATION_CVS_SASANIAN';

INSERT INTO Leader_Titles
				(LeaderType, 					GovernmentType, 							PolicyType,				LeaderTitle)
SELECT DISTINCT	'LEADER_CVS_BORAN',				GovernmentType, 							PolicyType,				LeaderTitle
FROM Civilization_Titles WHERE LeaderTitle LIKE "%FEMININE" AND CivilizationType = 'CIVILIZATION_CVS_SASANIAN';

INSERT INTO Leader_Titles
				(LeaderType, 					GovernmentType, 							PolicyType,				LeaderTitle)
SELECT DISTINCT	'LEADER_CVS_SHAPUR_I',			GovernmentType, 							PolicyType,				LeaderTitle
FROM Civilization_Titles WHERE LeaderTitle NOT LIKE "%FEMININE" AND CivilizationType = 'CIVILIZATION_CVS_SASANIAN';

