--==========================================================================================================================
-- Sasanian / Dynamic Modifiers
--==========================================================================================================================
-----------------------------------------------		
-- Promotion Class Types
-----------------------------------------------
INSERT INTO Types
		(Type,										Kind)
VALUES	('DYNMOD_SAILOR_UNIT_CLEAR_TERRAIN_MOVE',	'KIND_MODIFIER'),
		('DYNMOD_SAILOR_UNIT_COMBAT_STR',			'KIND_MODIFIER'),
		('DYNMOD_SAILOR_HUNTINGPARK_AMENITY',		'KIND_MODIFIER'),
		('DYNMOD_SAILOR_GRANT_UNITS_EXP',			'KIND_MODIFIER'),
		('DYNMOD_SAILOR_ATTACH_UNITS',				'KIND_MODIFIER'),
		('DYNMOD_SAILOR_GENERATE_MERCHANT',			'KIND_MODIFIER'),
		('DYNMOD_SAILOR_GRANT_POUCH_OF_GOLD',		'KIND_MODIFIER'),
		('DYNMOD_SAILOR_YIELD_PER_FOREIGN_POST',	'KIND_MODIFIER'),
		('DYNMOD_SAILOR_INCREASE_TRADE_ROUTES',		'KIND_MODIFIER'),
		('DYNMOD_SAILOR_ATTACH_CITIES',				'KIND_MODIFIER'),
		('DYNMOD_SAILOR_DISTRICT_GMP',				'KIND_MODIFIER'),
		('DYNMOD_SAILOR_PLOT_YIELDS',				'KIND_MODIFIER'),
-- Kawad
		('DYNMOD_SAILOR_TTBAM_GRANT_SPY_SLOT',		'KIND_MODIFIER'),
		('DYNMOD_SAILOR_TTBAM_DISTRICT_YIELD',		'KIND_MODIFIER'),
		('DYNMOD_SAILOR_TTBAM_OPERATION_CHANCE',	'KIND_MODIFIER'),
		('DYNMOD_SAILOR_ATTACH_SINGLE_CITY',		'KIND_MODIFIER'),
		('DYNMOD_SAILOR_DISTRICT_YIELD_VIA_APPEAL',	'KIND_MODIFIER'),
		('DYNMOD_SAILOR_TTBAM_PLOT_YIELD',			'KIND_MODIFIER'),
		('DYNMOD_SAILOR_TTBAM_ATTACH_ALL_PLAYERS',	'KIND_MODIFIER');
-----------------------------------------------
-- DynamicModifiers
-----------------------------------------------
INSERT INTO DynamicModifiers
		(ModifierType,								CollectionType,					EffectType)
VALUES	-- District Amenities from Entertainment
		('DYNMOD_SAILOR_HUNTINGPARK_AMENITY',		'COLLECTION_OWNER',				'EFFECT_ADJUST_DISTRICT_EXTRA_ENTERTAINMENT'),
		-- Clear Terrain Movement
		('DYNMOD_SAILOR_UNIT_CLEAR_TERRAIN_MOVE',	'COLLECTION_OWNER',				'EFFECT_ADJUST_UNIT_CLEAR_TERRAIN_START_MOVEMENT'),
		-- Unit Combat Strength
		('DYNMOD_SAILOR_UNIT_COMBAT_STR',			'COLLECTION_UNIT_COMBAT',		'EFFECT_ADJUST_PLAYER_STRENGTH_MODIFIER'),
		-- Grant Units Exp
		('DYNMOD_SAILOR_GRANT_UNITS_EXP',			'COLLECTION_PLAYER_UNITS',		'EFFECT_ADJUST_UNIT_GRANT_EXPERIENCE'),
		-- Attach Player Units
		('DYNMOD_SAILOR_ATTACH_UNITS',				'COLLECTION_PLAYER_UNITS',		'EFFECT_ATTACH_MODIFIER'),
		-- Great Person Points
		('DYNMOD_SAILOR_GENERATE_MERCHANT',			'COLLECTION_OWNER',				'EFFECT_ADJUST_GREAT_PERSON_POINTS'),
		-- Grant Yield
		('DYNMOD_SAILOR_GRANT_POUCH_OF_GOLD',		'COLLECTION_OWNER',				'EFFECT_GRANT_YIELD'),
		-- Trade Route Yield Per Post in Foreign City
		('DYNMOD_SAILOR_YIELD_PER_FOREIGN_POST',	'COLLECTION_OWNER',				'EFFECT_ADJUST_PLAYER_TRADE_ROUTE_YIELD_PER_POST_IN_FOREIGN_CITY'),
		-- Trade Route Capacity
		('DYNMOD_SAILOR_INCREASE_TRADE_ROUTES',		'COLLECTION_OWNER',				'EFFECT_ADJUST_TRADE_ROUTE_CAPACITY'),
		-- Attach Player Cities
		('DYNMOD_SAILOR_ATTACH_CITIES',				'COLLECTION_PLAYER_CITIES',		'EFFECT_ATTACH_MODIFIER'),
		-- Distrct Great Person Points
		('DYNMOD_SAILOR_DISTRICT_GMP',				'COLLECTION_PLAYER_DISTRICTS',	'EFFECT_ADJUST_DISTRICT_GREAT_PERSON_POINTS'),
		-- Plot Yields
		('DYNMOD_SAILOR_PLOT_YIELDS',				'COLLECTION_PLAYER_PLOT_YIELDS',	'EFFECT_ADJUST_PLOT_YIELD'),
-- Kawad
		-- Grant Spy
		('DYNMOD_SAILOR_TTBAM_GRANT_SPY_SLOT',		'COLLECTION_OWNER',				'EFFECT_GRANT_SPY'),
		-- District Yield
		('DYNMOD_SAILOR_TTBAM_DISTRICT_YIELD',		'COLLECTION_PLAYER_DISTRICTS',	'EFFECT_ADJUST_DISTRICT_YIELD_CHANGE'),
		-- Spy Operation Chance
		('DYNMOD_SAILOR_TTBAM_OPERATION_CHANCE',	'COLLECTION_PLAYER_UNITS',		'EFFECT_ADJUST_UNIT_SPY_OPERATION_CHANCE'),
		-- Attach Single City
		('DYNMOD_SAILOR_ATTACH_SINGLE_CITY',		'COLLECTION_OWNER',				'EFFECT_ATTACH_MODIFIER'),
		-- District Yield Based on Appeal
		('DYNMOD_SAILOR_DISTRICT_YIELD_VIA_APPEAL',	'COLLECTION_OWNER',				'EFFECT_ADJUST_DISTRICT_YIELD_BASED_ON_APPEAL'),
		-- Plot Yield
		('DYNMOD_SAILOR_TTBAM_PLOT_YIELD',			'COLLECTION_PLAYER_PLOT_YIELDS',	'EFFECT_ADJUST_PLOT_YIELD'),
		-- Attach All Players
		('DYNMOD_SAILOR_TTBAM_ATTACH_ALL_PLAYERS',	'COLLECTION_ALL_PLAYERS',		'EFFECT_ATTACH_MODIFIER');