--==========================================================================================================================
--
--            .
--            |\
--            | \
--            |  \
--            |   \
--            |    \          SASANIAN IRAN by CIVITAS
--            |     \
--            |      \
--            |       \       ____O
--            |        \     .' ./
--            |   _.,-~"\  .',/~'
--            <-~"   _.,-~" ~ |
--^"~-,._.,-~"^"~-,._\       /,._.,-~"^"~-,._.,-~"^"~-,._
--~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._
--^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._
--~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._.,-~"^"~-,._
--==========================================================================================================================
-- Sasanian / Defines
--==========================================================================================================================
-----------------------------------------------
-- Types
-----------------------------------------------
INSERT INTO Types	
		(Type,									Kind)
VALUES	('CIVILIZATION_SAILOR_SASANIAN',		'KIND_CIVILIZATION');
-----------------------------------------------
-- Civilizations
-----------------------------------------------	
INSERT INTO Civilizations	
		(CivilizationType,					Name,										Description,									Adjective,										StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity)
VALUES	('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CIVILIZATION_SAILOR_SASANIAN_NAME',	'LOC_CIVILIZATION_SAILOR_SASANIAN_DESCRIPTION',	'LOC_CIVILIZATION_SAILOR_SASANIAN_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	22,						'ETHNICITY_MEDIT');	
-----------------------------------------------			
-- CityNames			
-----------------------------------------------		
INSERT INTO CityNames	
		(CivilizationType,					CityName)	
VALUES	('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_GUNDESHAPUR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_ARBELA'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_GOR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_ISFAHAN'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_NISHAPUR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_MERV'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_DERBENT'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_GANZAK'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_NUSAYBIN'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_KIRKUK'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_RASHT'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_ZRANG'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_VAHMAN_ARDASHIR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_GURGAN'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_SHIRAGAN'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_HERAT'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_AMOL'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_DVIN'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_PARTAV'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_TBILISI'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_SHUSHTAR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_ISTAKHR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_SIRAF'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_DARABGERD'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_BUSHEHR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_BISHAPUR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_ARTEMITA'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_PEROZ_SHAPUR'),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_REV_ARDASHIR'),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_QESHM'),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_KAPUL'),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_SURA'),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_ERAN_ASAN_KAR_KAWAD'),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITY_NAME_SC_WEH_AZ_AMID_KAWAD');
-----------------------------------------------
-- CivilizationCitizenNames
-----------------------------------------------	
INSERT INTO CivilizationCitizenNames	
		(CivilizationType,					CitizenName,										Female,		Modern)
VALUES	('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_1',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_2',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_3',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_4',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_5',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_6',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_7',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_8',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_9',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MALE_10',				0,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_1',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_2',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_3',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_4',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_5',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_6',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_7',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_8',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_9',				1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_FEMALE_10',			1,			0),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_1',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_2',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_3',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_4',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_5',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_6',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_7',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_8',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_9',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_MALE_10',		0,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_1',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_2',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_3',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_4',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_5',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_6',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_7',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_8',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_9',		1,			1),
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CITIZEN_SAILOR_SASANIAN_MODERN_FEMALE_10',		1,			1);	
-----------------------------------------------			
-- CivilizationInfo			
-----------------------------------------------		
INSERT INTO CivilizationInfo	
		(CivilizationType,					Header,						Caption,									SortIndex)	
VALUES	('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_SAILOR_SASANIAN_LOCATION',		10),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_SAILOR_SASANIAN_SIZE',			20),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_SAILOR_SASANIAN_POPULATION',	30),	
		('CIVILIZATION_SAILOR_SASANIAN',	'LOC_CIVINFO_CAPITAL', 		'LOC_CIVINFO_SAILOR_SASANIAN_CAPITAL',		40);
-----------------------------------------------			
-- StartBias
-----------------------------------------------	
INSERT INTO StartBiasRivers
		(CivilizationType,					Tier)
VALUES	('CIVILIZATION_SAILOR_SASANIAN',	1);
