-----------------------------------------------
-- Types
-----------------------------------------------
INSERT INTO Types
		(Type,										Kind)
VALUES	('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'KIND_ABILITY');
-----------------------------------------------
-- TypeTags
-----------------------------------------------
INSERT INTO TypeTags
		(Type,										Tag)
VALUES	('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_RECON'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_MELEE'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_RANGED'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_SIEGE'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_HEAVY_CAVALRY'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_LIGHT_CAVALRY'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_ANTI_CAVALRY'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_HEAVY_CHARIOT'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'CLASS_LIGHT_CHARIOT');
-----------------------------------------------
-- UnitAbilities
-----------------------------------------------
INSERT INTO UnitAbilities
		(UnitAbilityType,							Name,										Description,								Inactive,	ShowFloatTextWhenEarned)
VALUES	('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'LOC_SAILOR_ABILITY_HUNTHONED_NAME',		'LOC_SAILOR_ABILITY_HUNTHONED_DESCRIPTION',	1,			1);
-----------------------------------------------
--  UnitAbilityModifiers
-----------------------------------------------
INSERT INTO	UnitAbilityModifiers
		(UnitAbilityType,							ModifierId)
VALUES	('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_1'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_2'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_3'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_4'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_5'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_6'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_7'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_8'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_9'),
		('ABILITY_SAILOR_HUNTINGPARK_HUNTHONED',	'SAILOR_HUNT_HONED_APPEAL_10');
-----------------------------------------------		
-- TraitModifiers		
-----------------------------------------------			
INSERT INTO TraitModifiers			
		(TraitType,								ModifierId)
VALUES	('TRAIT_CIVILIZATION_SAILOR_SOTSR',		'SAILOR_SOTSR_WISHKAR_HUNTHONED');
-----------------------------------------------		
-- Modifiers
-----------------------------------------------
INSERT INTO Modifiers -- Ability
		(ModifierId,								ModifierType,								RunOnce,		Permanent,		SubjectRequirementSetId)
VALUES	('SAILOR_HUNT_HONED_APPEAL_1',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_1'),
		('SAILOR_HUNT_HONED_APPEAL_2',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_2'),
		('SAILOR_HUNT_HONED_APPEAL_3',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_3'),
		('SAILOR_HUNT_HONED_APPEAL_4',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_4'),
		('SAILOR_HUNT_HONED_APPEAL_5',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_5'),
		('SAILOR_HUNT_HONED_APPEAL_6',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_6'),
		('SAILOR_HUNT_HONED_APPEAL_7',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_7'),
		('SAILOR_HUNT_HONED_APPEAL_8',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_8'),
		('SAILOR_HUNT_HONED_APPEAL_9',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_9'),
		('SAILOR_HUNT_HONED_APPEAL_10',				'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER',		0,				0,				'SAILOR_REQUIRES_TILE_APPEAL_10'),
		('SAILOR_HUNT_HONED_APPEAL_1_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_2_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_3_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_4_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_5_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_6_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_7_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_8_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_9_MODIFIER',		'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null),
		('SAILOR_HUNT_HONED_APPEAL_10_MODIFIER',	'DYNMOD_SAILOR_UNIT_COMBAT_STR',			0,				0,				null);

INSERT INTO Modifiers -- Trait
		(ModifierId,								ModifierType,								Permanent,		SubjectRequirementSetId)
VALUES	('SAILOR_SOTSR_WISHKAR_HUNTHONED',			'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		1,				'SAILOR_SOTSR_REQUIRES_UNIT_ON_WISHKAR');
-----------------------------------------------		
-- ModifierArguments
-----------------------------------------------
INSERT INTO ModifierArguments -- Ability
		(ModifierId,								Name,						Value)
VALUES	('SAILOR_HUNT_HONED_APPEAL_1',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_1_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_2',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_2_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_3',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_3_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_4',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_4_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_5',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_5_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_6',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_6_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_7',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_7_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_8',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_8_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_9',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_9_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_10',				'ModifierId',				'SAILOR_HUNT_HONED_APPEAL_10_MODIFIER'),
		('SAILOR_HUNT_HONED_APPEAL_1_MODIFIER',		'Amount',					1),
		('SAILOR_HUNT_HONED_APPEAL_2_MODIFIER',		'Amount',					2),
		('SAILOR_HUNT_HONED_APPEAL_3_MODIFIER',		'Amount',					3),
		('SAILOR_HUNT_HONED_APPEAL_4_MODIFIER',		'Amount',					4),
		('SAILOR_HUNT_HONED_APPEAL_5_MODIFIER',		'Amount',					5),
		('SAILOR_HUNT_HONED_APPEAL_6_MODIFIER',		'Amount',					6),
		('SAILOR_HUNT_HONED_APPEAL_7_MODIFIER',		'Amount',					7),
		('SAILOR_HUNT_HONED_APPEAL_8_MODIFIER',		'Amount',					8),
		('SAILOR_HUNT_HONED_APPEAL_9_MODIFIER',		'Amount',					9),
		('SAILOR_HUNT_HONED_APPEAL_10_MODIFIER',	'Amount',					10);

INSERT INTO ModifierArguments	-- Trait
		(ModifierId,								Name,						Value)
VALUES	('SAILOR_SOTSR_WISHKAR_HUNTHONED',			'AbilityType',				'ABILITY_SAILOR_HUNTINGPARK_HUNTHONED');
-----------------------------------------------		
-- RequirementSets
-----------------------------------------------
INSERT INTO RequirementSets -- Ability
		(RequirementSetId,							RequirementSetType)
VALUES	('SAILOR_REQUIRES_TILE_APPEAL_1',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_2',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_3',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_4',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_5',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_6',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_7',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_8',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_9',			'REQUIREMENTSET_TEST_ALL'),
		('SAILOR_REQUIRES_TILE_APPEAL_10',			'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSets -- Trait
		(RequirementSetId,							RequirementSetType)
VALUES	('SAILOR_SOTSR_REQUIRES_UNIT_ON_WISHKAR',	'REQUIREMENTSET_TEST_ANY');
-----------------------------------------------
-- RequirementSetRequirements
-----------------------------------------------
INSERT INTO RequirementSetRequirements -- Ability
		(RequirementSetId,							RequirementId)
VALUES	('SAILOR_REQUIRES_TILE_APPEAL_1',			'SAILOR_CHECK_APPEAL_IS_1'),
		('SAILOR_REQUIRES_TILE_APPEAL_1',			'SAILOR_CHECK_APPEAL_NOT_2'),

		('SAILOR_REQUIRES_TILE_APPEAL_2',			'SAILOR_CHECK_APPEAL_IS_2'),
		('SAILOR_REQUIRES_TILE_APPEAL_2',			'SAILOR_CHECK_APPEAL_NOT_3'),

		('SAILOR_REQUIRES_TILE_APPEAL_3',			'SAILOR_CHECK_APPEAL_IS_3'),
		('SAILOR_REQUIRES_TILE_APPEAL_3',			'SAILOR_CHECK_APPEAL_NOT_4'),

		('SAILOR_REQUIRES_TILE_APPEAL_4',			'SAILOR_CHECK_APPEAL_IS_4'),
		('SAILOR_REQUIRES_TILE_APPEAL_4',			'SAILOR_CHECK_APPEAL_NOT_5'),

		('SAILOR_REQUIRES_TILE_APPEAL_5',			'SAILOR_CHECK_APPEAL_IS_5'),
		('SAILOR_REQUIRES_TILE_APPEAL_5',			'SAILOR_CHECK_APPEAL_NOT_6'),

		('SAILOR_REQUIRES_TILE_APPEAL_6',			'SAILOR_CHECK_APPEAL_IS_6'),
		('SAILOR_REQUIRES_TILE_APPEAL_6',			'SAILOR_CHECK_APPEAL_NOT_7'),

		('SAILOR_REQUIRES_TILE_APPEAL_7',			'SAILOR_CHECK_APPEAL_IS_7'),
		('SAILOR_REQUIRES_TILE_APPEAL_7',			'SAILOR_CHECK_APPEAL_NOT_8'),

		('SAILOR_REQUIRES_TILE_APPEAL_8',			'SAILOR_CHECK_APPEAL_IS_8'),
		('SAILOR_REQUIRES_TILE_APPEAL_8',			'SAILOR_CHECK_APPEAL_NOT_9'),

		('SAILOR_REQUIRES_TILE_APPEAL_9',			'SAILOR_CHECK_APPEAL_IS_9'),
		('SAILOR_REQUIRES_TILE_APPEAL_9',			'SAILOR_CHECK_APPEAL_NOT_10'),

		('SAILOR_REQUIRES_TILE_APPEAL_10',			'SAILOR_CHECK_APPEAL_IS_10');

INSERT INTO RequirementSetRequirements -- Trait
		(RequirementSetId,							RequirementId)
VALUES  ('SAILOR_SOTSR_REQUIRES_UNIT_ON_WISHKAR',	'SAILOR_SOTSR_CHECK_FOR_WISHKAR'),
		('SAILOR_SOTSR_REQUIRES_UNIT_ON_WISHKAR',	'SAILOR_SOTSR_CHECK_FOR_ADJ_WISHKAR');
-----------------------------------------------
-- Requirements
-----------------------------------------------
INSERT INTO Requirements -- Ability
		(RequirementId,								RequirementType,						Inverse)
VALUES	('SAILOR_CHECK_APPEAL_IS_1',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_2',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_3',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_4',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_5',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_6',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_7',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_8',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_9',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),
		('SAILOR_CHECK_APPEAL_IS_10',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	0),

		('SAILOR_CHECK_APPEAL_NOT_2',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_3',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_4',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_5',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_6',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_7',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_8',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_9',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1),
		('SAILOR_CHECK_APPEAL_NOT_10',				'REQUIREMENT_PLOT_IS_APPEAL_BETWEEN',	1);

INSERT INTO Requirements -- Trait
		(RequirementId,								RequirementType,									Inverse)
VALUES	('SAILOR_SOTSR_CHECK_FOR_WISHKAR',			'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES',			0),
		('SAILOR_SOTSR_CHECK_FOR_ADJ_WISHKAR',		'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES',	0);
-----------------------------------------------
-- RequirementArguments
-----------------------------------------------
INSERT INTO RequirementArguments -- Ability
		(RequirementId,								Name,					Value)
VALUES	('SAILOR_CHECK_APPEAL_IS_1',				'MinimumAppeal',		1),
		('SAILOR_CHECK_APPEAL_IS_2',				'MinimumAppeal',		2),
		('SAILOR_CHECK_APPEAL_IS_3',				'MinimumAppeal',		3),
		('SAILOR_CHECK_APPEAL_IS_4',				'MinimumAppeal',		4),
		('SAILOR_CHECK_APPEAL_IS_5',				'MinimumAppeal',		5),
		('SAILOR_CHECK_APPEAL_IS_6',				'MinimumAppeal',		6),
		('SAILOR_CHECK_APPEAL_IS_7',				'MinimumAppeal',		7),
		('SAILOR_CHECK_APPEAL_IS_8',				'MinimumAppeal',		8),
		('SAILOR_CHECK_APPEAL_IS_9',				'MinimumAppeal',		9),
		('SAILOR_CHECK_APPEAL_IS_10',				'MinimumAppeal',		10),

		('SAILOR_CHECK_APPEAL_NOT_2',				'MinimumAppeal',		2),
		('SAILOR_CHECK_APPEAL_NOT_3',				'MinimumAppeal',		3),
		('SAILOR_CHECK_APPEAL_NOT_4',				'MinimumAppeal',		4),
		('SAILOR_CHECK_APPEAL_NOT_5',				'MinimumAppeal',		5),
		('SAILOR_CHECK_APPEAL_NOT_6',				'MinimumAppeal',		6),
		('SAILOR_CHECK_APPEAL_NOT_7',				'MinimumAppeal',		7),
		('SAILOR_CHECK_APPEAL_NOT_8',				'MinimumAppeal',		8),
		('SAILOR_CHECK_APPEAL_NOT_9',				'MinimumAppeal',		9),
		('SAILOR_CHECK_APPEAL_NOT_10',				'MinimumAppeal',		10);

INSERT INTO RequirementArguments -- Trait
		(RequirementId,								Name,				Value)
VALUES	('SAILOR_SOTSR_CHECK_FOR_WISHKAR',			'DistrictType',		'DISTRICT_SAILOR_HUNTINGPARK'),
		('SAILOR_SOTSR_CHECK_FOR_ADJ_WISHKAR',		'DistrictType',		'DISTRICT_SAILOR_HUNTINGPARK');
-----------------------------------------------
-- ModifierStrings
-----------------------------------------------
INSERT INTO ModifierStrings
		(ModifierId,								Context,		Text)
VALUES	('SAILOR_HUNT_HONED_APPEAL_1_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_2_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_3_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_4_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_5_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_6_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_7_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_8_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_9_MODIFIER',		'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}"),
		('SAILOR_HUNT_HONED_APPEAL_10_MODIFIER',	'Preview',		"+{1_Amount} {LOC_SAILOR_ABILITY_HUNTHONED_PREVIEW}");